version: 0.0
os: linux
files:
  - source: /
    destination: /opt/root/server

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode:777
    
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
      
