version: 0.2

phases:
    install:
        commands:
          - echo "Entering install phase..."
          - wget http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
          - sudo tar xzvf apache-maven-3.3.9-bin.tar.gz -C /opt/
          - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
    pre_build:
        commands:
            - echo "Pre_build"
    build:
        commands:
            - echo "Build"
            - mvn clean package
    post_build:
        commands:
            - echo "Post_build"
artifacts:
    files:
        - target/springtest.jar
        - appspec.yml
    discard-paths: yes        
